New nex-go
PretendoNetwork/friends-secure pull request #10
Opened 2023-11-12 11:52 UTC by jonbarrow

Draft since lots of things are changing still, but wanted to get this into more peoples hands

PR brings server up to date with the latest nex-go PR

2024-04-08 12:57 UTC, jonbarrow commented
Cemu seems to have some some DC issues, but I'm unsure if this is an us issue or a Cemu issue. Cemu would disconnect every few seconds and reconnect when in the friends applet

That said, I was connected via real hardware for around 30 minutes with no issue. Since real hardware is our main target, I'm fine with this

2024-04-08 20:19 UTC, DaniElectra commented
Are there any other `Scan` error checks that we would want to ignore for now?

2024-04-10 19:39 UTC, jonbarrow commented
> Are there any other `Scan` error checks that we would want to ignore for now?

Unsure. I just blindly added error checks to everything the linter said had them missing, I wasn't aware at the time that these didn't have defaults and were allowed to error

We really need to change that and give them defaults

2025-02-05 19:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PretendoNetwork/friends?pullRequest=10) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/PretendoNetwork/friends?pullRequest=10) before we can accept your contribution.<br/>**1** out of **6** committers have signed the CLA.<br/><br/>:white_check_mark: jonbarrow<br/>:x: MatthewL246<br/>:x: DaniElectra<br/>:x: wolfendale<br/>:x: mrjvs<br/>:x: imora7024<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PretendoNetwork/friends?pullRequest=10) it.</sub>

2025-02-16 04:40 UTC, jonbarrow commented
Marked as draft again since so much has changed, and this is largely untested right now. Will need someone like @hauntii to verify the 3DS parts as he's the one who designed them

2025-02-16 08:41 UTC, binaryoverload requested changes

2025-02-16 08:41 UTC, binaryoverload commented on Dockerfile
> +FROM golang:1.22-alpine3.20 AS build
The build is currently failing due to an outdated version of Docker:

`go: go.mod requires go >= 1.23.0 (running go 1.22.12; GOTOOLCHAIN=local)`

Please update this Dockerfile to use 1.23

```suggestion
FROM golang:1.23.6-alpine AS build
```

2025-02-17 00:17 UTC, merged